name: "Frontend test suite"

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - release/*
    paths:
      - '**/frontend/**/*.ts'
      - '**/frontend/**/*.js'
      - '**/frontend/**/*.json'

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**/frontend/**/*.ts'
      - '**/frontend/**/*.js'
      - '**/frontend/**/*.json'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./frontend

jobs:
  unit:
    name: Units (${{ matrix.browser }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: '22.15'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm i

      - name: Register plugins
        run: npm run ci:plugins:register_frontend

      - name: Install Playwright Browser
        run: npx playwright install --only-shell --with-deps ${{ matrix.browser }}

      - name: Test
        run: npm test -- --browsers ${{ matrix.browser }} --reporters dot --reporters github-actions
